# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:

  test:
    name: Test on go ${{ matrix.go_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      HOST: localhost
      PORT: 5433
      USER: root
      PASSWORD: root
      DBNAME: root
    strategy:
      matrix:
        go_version: ['1.18', '1.17', '>=1.18']
        os: [ubuntu-latest, ubuntu-18.04]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go_version }}
      

    # No passo chamado "Build-DB" (ou seja, "construir banco de dados"), 
    # rodaremos o comando docker-compose build para criar qualquer imagem necessária no Docker Compose, 
    # assim não precisamos nos preocupar com isso no futuro — podemos mudar a imagem do banco de dados sem problemas.      
    - name: Build-DB
      run: docker-compose build

    - name: Create-DB
      run: docker-compose up -d

    - name: Test
      run: go test -v main_test.go
      
 
 
  build:
    needs: test
    name: Build main GO on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Build
      run: go build -v main.go   
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        # Artifact name
        name: go_main_programa
        # A file, directory or wildcard pattern that describes what to upload
        path: main
      
      
  docker:
    needs: build
    uses: ./.github/workflows/Docker.yml
    secrets: inherit
